# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/teppei/mayfes/osakana_prj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/teppei/mayfes/osakana_prj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teppei/mayfes/osakana_prj/CMakeFiles /home/teppei/mayfes/osakana_prj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teppei/mayfes/osakana_prj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osakana_prj

# Build rule for target.
osakana_prj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osakana_prj
.PHONY : osakana_prj

# fast build rule for target.
osakana_prj/fast:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/build
.PHONY : osakana_prj/fast

src/behavior.o: src/behavior.cpp.o
.PHONY : src/behavior.o

# target to build an object file
src/behavior.cpp.o:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/behavior.cpp.o
.PHONY : src/behavior.cpp.o

src/behavior.i: src/behavior.cpp.i
.PHONY : src/behavior.i

# target to preprocess a source file
src/behavior.cpp.i:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/behavior.cpp.i
.PHONY : src/behavior.cpp.i

src/behavior.s: src/behavior.cpp.s
.PHONY : src/behavior.s

# target to generate assembly for a file
src/behavior.cpp.s:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/behavior.cpp.s
.PHONY : src/behavior.cpp.s

src/fish.o: src/fish.cpp.o
.PHONY : src/fish.o

# target to build an object file
src/fish.cpp.o:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/fish.cpp.o
.PHONY : src/fish.cpp.o

src/fish.i: src/fish.cpp.i
.PHONY : src/fish.i

# target to preprocess a source file
src/fish.cpp.i:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/fish.cpp.i
.PHONY : src/fish.cpp.i

src/fish.s: src/fish.cpp.s
.PHONY : src/fish.s

# target to generate assembly for a file
src/fish.cpp.s:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/fish.cpp.s
.PHONY : src/fish.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shark.o: src/shark.cpp.o
.PHONY : src/shark.o

# target to build an object file
src/shark.cpp.o:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/shark.cpp.o
.PHONY : src/shark.cpp.o

src/shark.i: src/shark.cpp.i
.PHONY : src/shark.i

# target to preprocess a source file
src/shark.cpp.i:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/shark.cpp.i
.PHONY : src/shark.cpp.i

src/shark.s: src/shark.cpp.s
.PHONY : src/shark.s

# target to generate assembly for a file
src/shark.cpp.s:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/shark.cpp.s
.PHONY : src/shark.cpp.s

src/teximage.o: src/teximage.cpp.o
.PHONY : src/teximage.o

# target to build an object file
src/teximage.cpp.o:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/teximage.cpp.o
.PHONY : src/teximage.cpp.o

src/teximage.i: src/teximage.cpp.i
.PHONY : src/teximage.i

# target to preprocess a source file
src/teximage.cpp.i:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/teximage.cpp.i
.PHONY : src/teximage.cpp.i

src/teximage.s: src/teximage.cpp.s
.PHONY : src/teximage.s

# target to generate assembly for a file
src/teximage.cpp.s:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/teximage.cpp.s
.PHONY : src/teximage.cpp.s

src/world.o: src/world.cpp.o
.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/osakana_prj.dir/build.make CMakeFiles/osakana_prj.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... osakana_prj"
	@echo "... rebuild_cache"
	@echo "... src/behavior.o"
	@echo "... src/behavior.i"
	@echo "... src/behavior.s"
	@echo "... src/fish.o"
	@echo "... src/fish.i"
	@echo "... src/fish.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shark.o"
	@echo "... src/shark.i"
	@echo "... src/shark.s"
	@echo "... src/teximage.o"
	@echo "... src/teximage.i"
	@echo "... src/teximage.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

